server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#####  swagger文档部分配置 ####
swagger:
  # 生产环境改为false（改为false后swagger-ui.html则无法访问）
  enabled: true
  docket:
    api-info:
      title: JsQns管理平台接口api
      description: 文件详细说明
      version: 1.0.0
      # 维护者信息
      contact:
        name: JsQns
        url: www.baidu.com
    base-package: com.js.summary
    group-name: "V2/api/03"


